name: tests-tickets

on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: cd tickets && npm install && npm run test:ci
